### ISSUE TITLE
是不是地址都已经不能用了？

### ISSUE THREAD

**Issue by mz320220** [waylau/free-vpn#3]
连接不上，提示Internet延迟，或网络连接到达上限。 😢

**Comment by waylau** [comment]
@mz320220  免费VPN 就是这样的，不是很稳定~

**Comment by yf-gogogo** [comment]
老哥，有没有收费的vpn账号，关键是稳定，如果尤其是像开十九大这种会的时候。。。

**Comment by waylau** [comment]
不可能存在绝对稳定的 VPN ~~
